<a href="https://colab.research.google.com/github/manusmriti31/Learning_PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello welcome to google collab!")

Hello welcome to google collab!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


 ## Introduction to Tensor
 ### Crating tensors
 Pythorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
 # Vector
 vector = torch.tensor([7,7])
 vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
 vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

TENSOR[1]

This will raise and out of index error

### Random tensors

why random tensors?

Random tensors are important because the way  many  neural networks learn is that they start with tensors full of rnadom numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6207, 0.7813, 0.2453, 0.4454],
        [0.7399, 0.7759, 0.5123, 0.8184],
        [0.9144, 0.2891, 0.4609, 0.8580]])

In [17]:
random_tensor_image_size = torch.rand(size = (224,224,3))
random_tensor_image_size.shape, random_tensor_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In the above we can see that in `torch.rand()` in one of the cells we have give as `torch.rand()` and in the other one we have given `torch.rnad(size = )` both the va

#Zeroes and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor o f all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# to get a rnage of numbers
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This has the format torch.arange(start=0,end,step=1)

In [22]:
#demonstrating different format of representation
range_demo1 = torch.arange(12,50,2)
range_demo2 = torch.arange(start = 10, end = 50, step = 2)
range_demo1, range_demo2

(tensor([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,
         48]),
 tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
         46, 48]))

In [23]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
 float_32_tensor = torch.tensor([3.0,6.1,9.0],dtype = None)
 float_32_tensor

tensor([3.0000, 6.1000, 9.0000])

In [25]:
float_32_tensor.dtype

torch.float32

#Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tesors not right shape
3. Tesnors not on the right device

In [26]:
# Float 32 tesor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (eg. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False # wheater or not to track gradients with this tensor operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information form tensors(tensor attributes)

1. Tensors not right datatype- to do get datatype form a tensro, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tenosr, cna use `tensor.shape`
3. Tensors not on the right device - to get deice from a tensor, can use `tensor.device`

In [29]:
# Creating a tensor
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.7419, 0.0669, 0.4346, 0.8550],
        [0.0875, 0.9058, 0.7072, 0.5669],
        [0.9267, 0.3643, 0.2346, 0.5015]])

In [30]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape) #some_tensor.size() `.size() is a function whereas .shape is an attribute
print(some_tensor.device)

tensor([[0.7419, 0.0669, 0.4346, 0.8550],
        [0.0875, 0.9058, 0.7072, 0.5669],
        [0.9267, 0.3643, 0.2346, 0.5015]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [31]:
# Create a tensor and perform the above oberations with the help of python functions
tensor = torch.tensor([1,2,3])
print(tensor)
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [32]:
# performing the same functions using PyTorch build in functions
print(torch.add(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.sub(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### Matrix Mulitplication

There are two main ways of matrix multiplication
1. Element wise multiplication
2. matrix multiplicatio (dot product)

In [33]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [35]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.47 ms, sys: 90 µs, total: 1.56 ms
Wall time: 1.38 ms


In [36]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 38 µs, sys: 7 µs, total: 45 µs
Wall time: 47.7 µs


tensor(14)

In [37]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(3,6)
torch.mm(tensor_A, tensor_B) #torch.mm is a short form for torch.matmul

tensor([[0.5295, 0.4955, 0.6558, 0.8000, 0.0511, 1.1916],
        [0.4652, 0.6772, 0.6029, 1.5154, 0.0855, 1.6962]])

## Transpose
This is used to switch the axes or dimmensions of a given tensor

To get the transopse of any matrix we use `Matrix_A.T`

In [38]:
tensor_B.shape

torch.Size([3, 6])

In [39]:
tensor_B.T.shape

torch.Size([6, 3])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [40]:
#create a tensor
x = torch.arange(1,101,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [41]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [42]:
#find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [43]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [44]:
#find the average
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

## Finding the positional min and max

In [45]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
 # Find the positon in the tensor which has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
 x.argmin()

tensor(0)

In [47]:
# Find the position in the tensor which has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to a definded shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squueze - removes all `1` dimension from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimmensions permutted (swapped) in a certain way

In [48]:
# Creating a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Add an extra dimmension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
#changing z changes x (becausse a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])