<a href="https://colab.research.google.com/github/manusmriti31/Learning_PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello welcome to google collab!")

Hello welcome to google collab!


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


 ## Introduction to Tensor
 ### Crating tensors
 Pythorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
 # Vector
 vector = torch.tensor([7,7])
 vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
 vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

TENSOR[1]

This will raise and out of index error

### Random tensors

why random tensors?

Random tensors are important because the way  many  neural networks learn is that they start with tensors full of rnadom numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3544, 0.5893, 0.0665, 0.2617],
        [0.1513, 0.7078, 0.2558, 0.8290],
        [0.6080, 0.4638, 0.9531, 0.2221]])

In [ ]:
random_tensor_image_size = torch.rand(size = (224,224,3))
random_tensor_image_size.shape, random_tensor_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In the above we can see that in `torch.rand()` in one of the cells we have give as `torch.rand()` and in the other one we have given `torch.rnad(size = )` both the va

#Zeroes and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor o f all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# to get a rnage of numbers
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This has the format torch.arange(start=0,end,step=1)

In [ ]:
#demonstrating different format of representation
range_demo1 = torch.arange(12,50,2)
range_demo2 = torch.arange(start = 10, end = 50, step = 2)
range_demo1, range_demo2

(tensor([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,
         48]),
 tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
         46, 48]))

In [ ]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
 float_32_tensor = torch.tensor([3.0,6.1,9.0],dtype = None)
 float_32_tensor

tensor([3.0000, 6.1000, 9.0000])

In [ ]:
float_32_tensor.dtype

torch.float32

#Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tesors not right shape
3. Tesnors not on the right device

In [ ]:
# Float 32 tesor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (eg. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False # wheater or not to track gradients with this tensor operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information form tensors(tensor attributes)

1. Tensors not right datatype- to do get datatype form a tensro, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tenosr, cna use `tensor.shape`
3. Tensors not on the right device - to get deice from a tensor, can use `tensor.device`

In [ ]:
# Creating a tensor
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.2522, 0.2616, 0.3700, 0.6925],
        [0.4690, 0.6907, 0.9439, 0.6325],
        [0.5079, 0.8393, 0.7070, 0.3641]])

In [ ]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape) #some_tensor.size() `.size() is a function whereas .shape is an attribute
print(some_tensor.device)

tensor([[0.2522, 0.2616, 0.3700, 0.6925],
        [0.4690, 0.6907, 0.9439, 0.6325],
        [0.5079, 0.8393, 0.7070, 0.3641]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and perform the above oberations with the help of python functions
tensor = torch.tensor([1,2,3])
print(tensor)
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [ ]:
# performing the same functions using PyTorch build in functions
print(torch.add(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.sub(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### Matrix Mulitplication

There are two main ways of matrix multiplication
1. Element wise multiplication
2. matrix multiplicatio (dot product)

In [ ]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 722 µs, sys: 775 µs, total: 1.5 ms
Wall time: 1.51 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 33 µs, sys: 5 µs, total: 38 µs
Wall time: 42.2 µs


tensor(14)

In [ ]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(3,6)
torch.mm(tensor_A, tensor_B) #torch.mm is a short form for torch.matmul

tensor([[0.7358, 1.5181, 0.9779, 0.2529, 1.1406, 1.6251],
        [0.5994, 0.7596, 0.5100, 0.1561, 0.7088, 0.8712]])

## Transpose
This is used to switch the axes or dimmensions of a given tensor

To get the transopse of any matrix we use `Matrix_A.T`

In [ ]:
tensor_B.shape

torch.Size([3, 6])

In [ ]:
tensor_B.T.shape

torch.Size([6, 3])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#create a tensor
x = torch.arange(1,101,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
#find the average
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
 # Find the positon in the tensor which has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
 x.argmin()

tensor(0)

In [ ]:
# Find the position in the tensor which has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to a definded shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squueze - removes all `1` dimension from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimmensions permutted (swapped) in a certain way

In [ ]:
# Creating a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimmension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x (becausse a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove exttra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific
print(f"Previous traget: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimmention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed2 = torch.unsqueeze(x_squeezed,0)
print(f"New tensor 1: {x_unsqueezed}")
print(f"New tensor 2: {x_unsqueezed2}")
print(f"New Shape 1 : {x_unsqueezed.shape}")
print(f"New Shape 2 : {x_unsqueezed2.shape}")

Previous traget: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor 1: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New tensor 2: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape 1 : torch.Size([1, 9])
New Shape 2 : torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(224,224,3)

# Permute the original tensor to rearragne the axis (or dim) order
x_permutted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permutted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 3
x_original


tensor([[[3.0000, 0.0904, 0.2877],
         [0.6668, 0.1682, 0.5646],
         [0.3478, 0.5309, 0.8136],
         ...,
         [0.6076, 0.4108, 0.8717],
         [0.2392, 0.6078, 0.1654],
         [0.1016, 0.7394, 0.1827]],

        [[0.6455, 0.6383, 0.4232],
         [0.0125, 0.4173, 0.9170],
         [0.3231, 0.7889, 0.9143],
         ...,
         [0.3686, 0.1154, 0.5140],
         [0.8503, 0.9541, 0.4165],
         [0.7615, 0.4781, 0.3163]],

        [[0.9596, 0.4769, 0.8433],
         [0.3025, 0.4281, 0.5300],
         [0.0369, 0.4954, 0.9812],
         ...,
         [0.2684, 0.8902, 0.6271],
         [0.3026, 0.9672, 0.4719],
         [0.6094, 0.6722, 0.7064]],

        ...,

        [[0.1580, 0.9420, 0.9549],
         [0.7673, 0.6464, 0.9235],
         [0.0889, 0.6532, 0.5795],
         ...,
         [0.5419, 0.0244, 0.4787],
         [0.8242, 0.9727, 0.7230],
         [0.9185, 0.1472, 0.4763]],

        [[0.8922, 0.4462, 0.9924],
         [0.1281, 0.6766, 0.9009],
         [0.

In [ ]:
x_permutted

tensor([[[3.0000, 0.6668, 0.3478,  ..., 0.6076, 0.2392, 0.1016],
         [0.6455, 0.0125, 0.3231,  ..., 0.3686, 0.8503, 0.7615],
         [0.9596, 0.3025, 0.0369,  ..., 0.2684, 0.3026, 0.6094],
         ...,
         [0.1580, 0.7673, 0.0889,  ..., 0.5419, 0.8242, 0.9185],
         [0.8922, 0.1281, 0.3587,  ..., 0.7738, 0.3907, 0.5419],
         [0.2843, 0.6818, 0.1660,  ..., 0.3741, 0.4303, 0.0494]],

        [[0.0904, 0.1682, 0.5309,  ..., 0.4108, 0.6078, 0.7394],
         [0.6383, 0.4173, 0.7889,  ..., 0.1154, 0.9541, 0.4781],
         [0.4769, 0.4281, 0.4954,  ..., 0.8902, 0.9672, 0.6722],
         ...,
         [0.9420, 0.6464, 0.6532,  ..., 0.0244, 0.9727, 0.1472],
         [0.4462, 0.6766, 0.5319,  ..., 0.6614, 0.8091, 0.6748],
         [0.2086, 0.6707, 0.0358,  ..., 0.8699, 0.0224, 0.6197]],

        [[0.2877, 0.5646, 0.8136,  ..., 0.8717, 0.1654, 0.1827],
         [0.4232, 0.9170, 0.9143,  ..., 0.5140, 0.4165, 0.3163],
         [0.8433, 0.5300, 0.9812,  ..., 0.6271, 0.4719, 0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Creating a new tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select " all" of a target dimmension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[:,0,:]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimmension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
 # Get index 0 of 0th and 1st dimension and all values of 2nd dimension
 x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# indexing on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
array = np.arange(1,8)
tensor = torch.from_numpy(array) # to concert to the default dtype `type(torch.float32)`
# when converting from numpy to pytorch, it refelects numpy's default datatype of float64 unless specified, whereas the default datatype of tensor is float32
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
# change the value of array what will it do to the `tensor`
array = array +1
array,tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

Thus creating a tensor from numpy leads to the creation of a new tensor, thus the new tensor does not change if you change the original array

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f"The orignal tensor is: {tensor}")
print(f"The NumPy converted form tensor is: {numpy_tensor}")
print(f"The data type of the converted numpy is {numpy_tensor.dtype}")

The orignal tensor is: tensor([1., 1., 1., 1., 1., 1., 1.])
The NumPy converted form tensor is: [1. 1. 1. 1. 1. 1. 1.]
The data type of the converted numpy is float32


In [ ]:
#change the tensor and what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

We can see here that even after changing the original tensor there is no change in the array which was made from the tensor
Thus a new copy is created in the memory when converting from tenosr to numpy, thus changing the original tensor will not change the array

In [ ]:
## Reproducibility (trying to take random out of random)

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed
