<a href="https://colab.research.google.com/github/manusmriti31/Learning_PyTorch/blob/main/Exercise/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# Read both the douments

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
import torch
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.5380, 0.0262, 0.8992, 0.4927, 0.6038, 0.4174, 0.5800],
        [0.8007, 0.8506, 0.2305, 0.2142, 0.7266, 0.5821, 0.3532],
        [0.6246, 0.0611, 0.9887, 0.1331, 0.9636, 0.4939, 0.8893],
        [0.4653, 0.7443, 0.3966, 0.8243, 0.0272, 0.7733, 0.5316],
        [0.0376, 0.5317, 0.9636, 0.5796, 0.4346, 0.4528, 0.2457],
        [0.3553, 0.9365, 0.5013, 0.3907, 0.4920, 0.6598, 0.7885],
        [0.5002, 0.0464, 0.4052, 0.1718, 0.1983, 0.2076, 0.9061]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
tensor2 = torch.rand(1,7)
print(tensor2)
print(tensor1)
print("The matrix multiplication of both the tensors is:")
torch.mm(tensor1,tensor2.T)


tensor([[0.9347, 0.6431, 0.6969, 0.7321, 0.9181, 0.5652, 0.7417]])
tensor([[0.5380, 0.0262, 0.8992, 0.4927, 0.6038, 0.4174, 0.5800],
        [0.8007, 0.8506, 0.2305, 0.2142, 0.7266, 0.5821, 0.3532],
        [0.6246, 0.0611, 0.9887, 0.1331, 0.9636, 0.4939, 0.8893],
        [0.4653, 0.7443, 0.3966, 0.8243, 0.0272, 0.7733, 0.5316],
        [0.0376, 0.5317, 0.9636, 0.5796, 0.4346, 0.4528, 0.2457],
        [0.3553, 0.9365, 0.5013, 0.3907, 0.4920, 0.6598, 0.7885],
        [0.5002, 0.0464, 0.4052, 0.1718, 0.1983, 0.2076, 0.9061]])
The matrix multiplication of both the tensors is:


tensor([[2.7276],
        [2.8710],
        [3.2331],
        [2.6499],
        [2.3103],
        [2.9793],
        [1.8770]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(7,7)

#torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)

print(f"\nThe tensors are:\n\nTensor 1: \n{tensor1}\n\nTensor 2: \n{tensor2}\n")
print("The matrix multiplication of the two tensors are:")
print(torch.mm(tensor1, tensor2.T))



The tensors are:

Tensor 1: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

Tensor 2: 
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

The matrix multiplication of the two tensors are:
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
torch.cuda.manual_seed(1234)
torch.cuda.initial_seed()

1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
torch.manual_seed(1234)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)
print(tensor1)
print(tensor2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
tensor3 = torch.mm(tensor1,tensor2.T)
tensor3,tensor3.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [31]:
tensor3.max(),tensor3.min()


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
tensor3.argmax(),tensor3.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
torch.manual_seed(7)
tensor4 = torch.rand(1,1,1,10)
print(tensor4)
tensor5 = tensor4.squeeze()
print(tensor5)
tensor4.shape, tensor5.shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


(torch.Size([1, 1, 1, 10]), torch.Size([10]))